version: "3.9"
services:
  mysql:
    container_name: "server-mysql"
    restart: unless-stopped
    hostname: "docker-mysql"
    build:
      context: ./mysql
    ports:
      - "3306:3306"
  app:
    container_name: "server-app"
    restart: unless-stopped
    depends_on:
      - elasticsearch
    command: sh -c "/app/wait-for-it.sh server-mysql:3306 -t 10 && npm test && npm start"
    build:
      context: ./app
    ports:
      - "8001:8001"
  nginx:
    container_name: "server-nginx"
    restart: always
    depends_on:
      - app
    build:
      context: ./nginx
    ports:
      - "8000:80"
  elasticsearch:
    container_name: "server-elasticsearch"
    build: ./elasticsearch
    depends_on:
      - mysql
    # volumes:
    #   - ./elasticsearch/_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  grafana:
    container_name: "server-grafana"
    build: ./grafana
    # volumes:
    #   - ./grafana/_data:/var/lib/grafana
    ports:
      - 3000:3000
