version: "3.9"
services:
  mysql:
    container_name: "server-mysql"
    restart: unless-stopped
    hostname: "docker-mysql"
    build:
      context: ./mysql
    ports:
      - "3306:3306"
  app:
    container_name: "server-app"
    restart: unless-stopped
    depends_on:
      - mysql
    command: sh -c "./wait-for-it.sh server-mysql:3306 -t 10 && npm start"
    build:
      context: ./app
    ports:
      - "8001:8001"
  nginx:
    container_name: "server-nginx"
    restart: always
    depends_on:
      - app
    build:
      context: ./nginx
    ports:
      - "8000:80"
